---
swagger: '2.0'
info:
  version: '1.0'
  title: Hello World API
paths:
  "/execution":
    post:
      description: starts execution of a state machine
      responses:
        '200':
          headers:
            Content-Type:
              type: string
              description: Media type of request